#!/usr/bin/env python3
"""Launchpad generator.

Reads the user's declarative config at ~/.config/omarchy/launchpad.json and
emits a Hyprland Lua file at ~/.config/hypr/launchpad.lua that:

  1. Pins each app to its workspace via o.window(match, { workspace = ... }),
     using the documented o.* helpers so it survives Omarchy updates.
  2. Auto-launches apps flagged with "launchAtBoot" at login via
     o.launch_on_start(command) (uwsm-app wrapper).

It then ensures ~/.config/hypr/hyprland.lua requires the generated file
(idempotent), and reloads Hyprland so the rules take effect.

This script lives in the plugin bundle. It only ever WRITES into
~/.config/hypr/ (user config) and READS ~/.config/omarchy/launchpad.json
(user data). It never touches /usr/share/omarchy.

Window-rule syntax reference (verified against the Hyprland wiki,
https://wiki.hypr.land/Configuring/Basics/Window-Rules/, Hyprland 0.56.x):
the action property is `workspace [string]` and may be suffixed with
" silent" to suppress the workspace switch. o.window() forwards a
`workspace` key in its rules table to hl.window_rule, producing
`workspace <n>` / `workspace <n> silent`.
"""

import json
import os
import shutil
import subprocess
import sys

HOME = os.environ.get("HOME", os.path.expanduser("~"))
CONFIG_DIR = os.path.join(HOME, ".config")
OMARCHY_DIR = os.path.join(CONFIG_DIR, "omarchy")
HYPR_DIR = os.path.join(CONFIG_DIR, "hypr")

USER_CONFIG = os.path.join(OMARCHY_DIR, "launchpad.json")
GENERATED_LUA = os.path.join(HYPR_DIR, "launchpad.lua")
HYPRLAND_LUA = os.path.join(HYPR_DIR, "hyprland.lua")
REQUIRE_LINE = 'require("hypr.launchpad")'


def log(msg: str) -> None:
    print(f"[launchpad] {msg}")


def load_user_config():
    if not os.path.exists(USER_CONFIG):
        log(f"no config at {USER_CONFIG}; emitting empty ruleset")
        return {"version": 1, "entries": []}
    try:
        with open(USER_CONFIG, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        log(f"ERROR: could not read {USER_CONFIG}: {exc}")
        sys.exit(1)
    if not isinstance(data, dict):
        log("ERROR: config root must be a JSON object")
        sys.exit(1)
    entries = data.get("entries", [])
    if not isinstance(entries, list):
        log("ERROR: 'entries' must be a JSON array")
        sys.exit(1)
    return data


def validate_entry(entry, idx):
    if not isinstance(entry, dict):
        log(f"ERROR: entry #{idx} is not an object; skipping")
        return None
    app_id = entry.get("id") or entry.get("match") or f"entry#{idx}"
    match = entry.get("match")
    command = entry.get("command")
    workspace = entry.get("workspace")
    launch_at_boot = bool(entry.get("launchAtBoot", False))

    if not match:
        log(f"ERROR: entry '{app_id}' missing 'match'; skipping")
        return None
    if workspace is None and not launch_at_boot:
        log(f"ERROR: entry '{app_id}' has neither 'workspace' nor 'launchAtBoot'; skipping")
        return None
    if workspace is not None and not isinstance(workspace, int):
        # Accept ints (1, 2, ...). Strings like "2" are coerced.
        try:
            workspace = int(workspace)
        except (TypeError, ValueError):
            log(f"ERROR: entry '{app_id}' workspace must be an integer; skipping")
            return None
    if launch_at_boot and not command:
        log(f"ERROR: entry '{app_id}' sets launchAtBoot but has no 'command'; skipping")
        return None
    return {
        "id": app_id,
        "match": match,
        "command": command,
        "workspace": workspace,
        "launchAtBoot": launch_at_boot,
        "silent": bool(entry.get("silent", False)),
    }


def generate_lua(entries):
    lines = []
    lines.append("-- Auto-generated by the Launchpad plugin. DO NOT EDIT BY HAND.")
    lines.append("-- Source of truth: ~/.config/omarchy/launchpad.json")
    lines.append("-- Regenerate with: launchpad.json -> scripts/generate.py")
    lines.append("")
    lines.append('require("default.hypr.helpers")')
    lines.append("")
    count_rules = 0
    count_boot = 0
    for e in entries:
        if e["workspace"] is not None:
            # o.window(match, { workspace = "N" }) -> workspace pin rule.
            # Suffix " silent" keeps the current workspace focused.
            ws_value = f'"{e["workspace"]}{" silent" if e["silent"] else ""}"'
            lines.append(f'-- Pin {e["id"]} to workspace {e["workspace"]}')
            lines.append(f'o.window({e["match"]!r}, {{ workspace = {ws_value} }})')
            count_rules += 1
        if e["launchAtBoot"]:
            # o.launch_on_start wraps the command with uwsm-app and fires on
            # hyprland.start.
            lines.append(f'-- Launch {e["id"]} at boot')
            lines.append(f'o.launch_on_start({e["command"]!r})')
            count_boot += 1
        lines.append("")
    lines.append(f"-- Applied {count_rules} workspace rule(s) and {count_boot} boot launch(es).")
    return "\n".join(lines) + "\n"


def backup_and_write(path, content):
    if os.path.exists(path):
        stamp = subprocess.run(
            ["date", "+%s"], capture_output=True, text=True
        ).stdout.strip()
        bak = f"{path}.bak.{stamp}"
        shutil.copy2(path, bak)
        log(f"backed up existing {path} -> {bak}")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    log(f"wrote {path}")


def ensure_required():
    if not os.path.exists(HYPRLAND_LUA):
        log(f"WARNING: {HYPRLAND_LUA} not found; cannot inject require")
        return
    with open(HYPRLAND_LUA, "r", encoding="utf-8") as fh:
        existing = fh.read()
    if REQUIRE_LINE in existing:
        return
    # Append the require at the end of the user hyprland.lua.
    with open(HYPRLAND_LUA, "a", encoding="utf-8") as fh:
        fh.write("\n" + REQUIRE_LINE + "  -- Launchpad: app -> workspace pinning\n")
    log(f"appended '{REQUIRE_LINE}' to {HYPRLAND_LUA}")


def reload_hyprland():
    # Best-effort reload. Validate config errors after.
    try:
        subprocess.run(["hyprctl", "reload"], check=False, timeout=10)
        log("hyprctl reload dispatched")
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        log(f"WARNING: could not run hyprctl reload: {exc}")


def report_config_errors():
    try:
        res = subprocess.run(
            ["hyprctl", "configerrors"], capture_output=True, text=True, timeout=10
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        log(f"WARNING: could not run hyprctl configerrors: {exc}")
        return
    out = (res.stdout or "").strip()
    if not out:
        log("hyprctl configerrors: clean (no errors)")
    else:
        log("hyprctl configerrors reported:\n" + out)


def main():
    data = load_user_config()
    validated = []
    for idx, raw in enumerate(data.get("entries", [])):
        e = validate_entry(raw, idx)
        if e:
            validated.append(e)
    lua = generate_lua(validated)
    backup_and_write(GENERATED_LUA, lua)
    ensure_required()
    reload_hyprland()
    report_config_errors()
    log(f"done: {len(validated)} valid entr(ies) applied")


if __name__ == "__main__":
    main()
